# Default environment (can override with env param)
URL=https://online.actitime.com/mstar/login.do
BROWSER=chrome

GRID=false
GRID_URL=http://localhost:4444/wd/hub
HEADLESS=false
ImplicitTimeOut=10

EMAIL_FROM=rohit.lavate287@gmail.com
EMAIL_PASSWORD=app-password
EMAIL_TO=rohitlavate97@gmail.com,lavatero92@gmail.com
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
